version: "3"

services:
  webserver:
    build:
      context: .
      dockerfile: ./Dockerfile.webserver
    container_name: web-g6-webserver
    ports:
      - 8081:8081
    volumes:
      - ./webserver/contents:/usr/share/nginx/html/contents

  app:
    depends_on:
      - webserver
    build:
      context: .
      dockerfile: ./Dockerfile.app
    container_name: web-g6-app
    ports:
      - 8080:8080
    volumes:
      - .:/run/web-g6
      - /run/web-g6/node_modules/
    environment:
      - CHOKIDAR_USEPOLLING=true